#! /bin/sh

sxhkd &
fcitx &
xset b off
ntpdate time.pool.aliyun.com
# feh --bg-scale /home/james/Pictures/girl.jpg
feh --bg-scale /usr/share/backgrounds/b-mountains.jpg
# feh --bg-scale /usr/share/backgrounds/xfce/dreams.jpg
# $HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a tilda state=floating
bspc rule -a xeyes state=floating
bspc rule -a Zathura state=tiled
$HOME/.config/polybar/launch1.sh &
compton -b --backend glx
# picom --experimental-backends --backend glx -b
# $HOME/Pictures/Background/auto-change.sh &
# autolock if no action of 10 minutes
# if you want to avoid it, just move your cursor to one of the corner of screen
# xautolock -time 10 -locker '/usr/bin/lock' -corners ---- -cornersize 30 &
